PARAMETER ANNUITYC(CCC) 'Transforms investment to annual payment (fraction)'        
* Thus, for instance, an investment of 100, paid over 20 years,                     
* at the end of the year assuming an interest rate of 5%,                           
* will imply an annual payment of 8.02,                                             
* hence, ANNUITYC should in this case have the value 0.0802.                        
* Unit: (none).                                                                     
* The present value 0.094 corressponds to 20 years and 7%                           
/                                                                                   
AUSTRIA                                                                      0.0802 
BELGIUM                                                                      0.0802 
BULGARIA                                                                     0.0802 
CROATIA                                                                      0.0802 
CYPRUS                                                                       0.0802 
CZECHIA                                                                      0.0802 
DENMARK                                                                      0.0802 
ESTONIA                                                                      0.0802 
FINLAND                                                                      0.0802 
FRANCE                                                                       0.0802 
GERMANY                                                                      0.0802 
GREECE                                                                       0.0802 
HUNGARY                                                                      0.0802 
IRELAND                                                                      0.0802 
ITALY                                                                        0.0802 
LATVIA                                                                       0.0802 
LITHUANIA                                                                    0.0802 
LUXEMBOURG                                                                   0.0802 
MALTA                                                                        0.0802 
NETHERLANDS                                                                  0.0802 
NORWAY                                                                       0.0802 
POLAND                                                                       0.0802 
PORTUGAL                                                                     0.0802 
ROMANIA                                                                      0.0802 
SLOVAKIA                                                                     0.0802 
SLOVENIA                                                                     0.0802 
SPAIN                                                                        0.0802 
SWEDEN                                                                       0.0802 
SWITZERLAND                                                                  0.0802 
UNITED_KINGDOM                                                               0.0802 
/;                                                                                  
