SET CCCRRR(CCC,RRR) "Regions in countries"                        
/                                                                 
AUSTRIA                                                .    AT    
BELGIUM                                                .    BE    
BULGARIA                                               .    BG    
CROATIA                                                .    HR    
CYPRUS                                                 .    CY    
CZECHIA                                                .    CZ    
DENMARK                                                .    DK    
ESTONIA                                                .    EE    
FINLAND                                                .    FI    
FRANCE                                                 .    FR    
GERMANY                                                .    DE    
GREECE                                                 .    GR    
HUNGARY                                                .    HU    
IRELAND                                                .    IE    
ITALY                                                  .    IT    
LATVIA                                                 .    LV    
LITHUANIA                                              .    LT    
LUXEMBOURG                                             .    LU    
MALTA                                                  .    MT    
NETHERLANDS                                            .    NL    
NORWAY                                                 .    NO    
POLAND                                                 .    PO    
PORTUGAL                                               .    PT    
ROMANIA                                                .    RO    
SLOVAKIA                                               .    SK    
SLOVENIA                                               .    SI    
SPAIN                                                  .    ES    
SWEDEN                                                 .    SE    
SWITZERLAND                                            .    CH    
UNITED_KINGDOM                                         .    UK    
NORTH_SEA                                              .    HUB   
/;                                                                
