PARAMETER DEFP_BASE(RRR)  'Nominal annual average consumer electricity price (including taxes) in the base year (Money/MWh)'         
/                                                                                                                                    
AT                                                                                                                           40      
BE                                                                                                                           40      
BG                                                                                                                           40      
CH                                                                                                                           40      
CY                                                                                                                           40      
CZ                                                                                                                           40      
DE                                                                                                                           40      
DK                                                                                                                           40      
EE                                                                                                                           40      
ES                                                                                                                           40      
FI                                                                                                                           40      
FR                                                                                                                           40      
GR                                                                                                                           40      
HR                                                                                                                           40      
HU                                                                                                                           40      
IE                                                                                                                           40      
IT                                                                                                                           40      
LT                                                                                                                           40      
LU                                                                                                                           40      
LV                                                                                                                           40      
MT                                                                                                                           40      
NL                                                                                                                           40      
NO                                                                                                                           40      
PO                                                                                                                           40      
PT                                                                                                                           40      
RO                                                                                                                           40      
SE                                                                                                                           40      
SI                                                                                                                           40      
SK                                                                                                                           40      
UK                                                                                                                           40      
/;                                                                                                                                   
