PARAMETER DHFP_BASE(AAA)  'Nominal annual average consumer heat price (including taxes) in the base year (Money/MWh)'                 
/                                                                                                                                     
AT_A                                                                                                                  6.47            
BE_A                                                                                                                  6.47            
BE_Offshore                                                                                                           6.47            
BG_A                                                                                                                  6.47            
CH_A                                                                                                                  6.47            
CY_A                                                                                                                  6.47            
CY_Offshore                                                                                                           6.47            
CZ_A                                                                                                                  6.47            
DE_A                                                                                                                  6.47            
DE_Offshore                                                                                                           6.47            
DK_A                                                                                                                  6.47            
DK_Offshore                                                                                                           6.47            
EE_A                                                                                                                  6.47            
EE_Offshore                                                                                                           6.47            
ES_A                                                                                                                  6.47            
ES_Offshore                                                                                                           6.47            
FI_A                                                                                                                  6.47            
FI_Offshore                                                                                                           6.47            
FR_A                                                                                                                  6.47            
FR_Offshore                                                                                                           6.47            
GR_A                                                                                                                  6.47            
GR_Offshore                                                                                                           6.47            
HR_A                                                                                                                  6.47            
HR_Offshore                                                                                                           6.47            
HU_A                                                                                                                  6.47            
IE_A                                                                                                                  6.47            
IE_Offshore                                                                                                           6.47            
IT_A                                                                                                                  6.47            
IT_Offshore                                                                                                           6.47            
LT_A                                                                                                                  6.47            
LT_Offshore                                                                                                           6.47            
LU_A                                                                                                                  6.47            
LV_A                                                                                                                  6.47            
LV_Offshore                                                                                                           6.47            
MT_A                                                                                                                  6.47            
MT_Offshore                                                                                                           6.47            
NL_A                                                                                                                  6.47            
NL_Offshore                                                                                                           6.47            
NO_A                                                                                                                  6.47            
NO_Offshore                                                                                                           6.47            
PO_A                                                                                                                  6.47            
PO_Offshore                                                                                                           6.47            
PT_A                                                                                                                  6.47            
PT_Offshore                                                                                                           6.47            
RO_A                                                                                                                  6.47            
SE_A                                                                                                                  6.47            
SE_Offshore                                                                                                           6.47            
SI_A                                                                                                                  6.47            
SK_A                                                                                                                  6.47            
UK_A                                                                                                                  6.47            
UK_Offshore                                                                                                           6.47            
/;                                                                                                                                    
                                                                                                                                      
DHFP_BASE(AAA)$(DHFP_BASE(AAA) EQ 0)= DHFP_BASE('AT_A');                                                                              
                                                                                                                                      
