PARAMETER DISCOST_E(RRR)  'Cost of electricity distribution (Money/MWh)'     
* apparently not used in BB4, only DISLOSS                                   
/                                                                            
AT                                                                       5   
BE                                                                       5   
BG                                                                       5   
CH                                                                       5   
CY                                                                       5   
CZ                                                                       5   
DE                                                                       5   
DK                                                                       5   
EE                                                                       5   
ES                                                                       5   
FI                                                                       5   
FR                                                                       5   
GR                                                                       5   
HR                                                                       5   
HU                                                                       5   
IE                                                                       5   
IT                                                                       5   
LT                                                                       5   
LU                                                                       5   
LV                                                                       5   
MT                                                                       5   
NL                                                                       5   
NO                                                                       5   
PO                                                                       5   
PT                                                                       5   
RO                                                                       5   
SE                                                                       5   
SI                                                                       5   
SK                                                                       5   
UK                                                                       5   
/;                                                                           
