PARAMETER DISCOST_H(AAA)  'Cost of heat distribution (Money/MWh)'     
* Areas merged, average values used                                   
* apparently not used in BB4 benutzt, only DISLOSS                    
/                                                                     
AT_A                                                              2   
BE_A                                                              2   
BE_Offshore                                                       2   
BG_A                                                              2   
CH_A                                                              2   
CY_A                                                              2   
CY_Offshore                                                       2   
CZ_A                                                              2   
DE_A                                                              2   
DE_Offshore                                                       2   
DK_A                                                              2   
DK_Offshore                                                       2   
EE_A                                                              2   
EE_Offshore                                                       2   
ES_A                                                              2   
ES_Offshore                                                       2   
FI_A                                                              2   
FI_Offshore                                                       2   
FR_A                                                              2   
FR_Offshore                                                       2   
GR_A                                                              2   
GR_Offshore                                                       2   
HR_A                                                              2   
HR_Offshore                                                       2   
HU_A                                                              2   
IE_A                                                              2   
IE_Offshore                                                       2   
IT_A                                                              2   
IT_Offshore                                                       2   
LT_A                                                              2   
LT_Offshore                                                       2   
LU_A                                                              2   
LV_A                                                              2   
LV_Offshore                                                       2   
MT_A                                                              2   
MT_Offshore                                                       2   
NL_A                                                              2   
NL_Offshore                                                       2   
NO_A                                                              2   
NO_Offshore                                                       2   
PO_A                                                              2   
PO_Offshore                                                       2   
PT_A                                                              2   
PT_Offshore                                                       2   
RO_A                                                              2   
SE_A                                                              2   
SE_Offshore                                                       2   
SI_A                                                              2   
SK_A                                                              2   
UK_A                                                              2   
UK_Offshore                                                       2   
/;                                                                    
