PARAMETER DISLOSS_E(RRR)  'Loss in electricity distribution'      
/                                                                 
AT                                                           0.032
BE                                                           0.032
BG                                                           0.032
CH                                                           0.032
CY                                                           0.032
CZ                                                           0.032
DE                                                           0.032
DK                                                           0.032
EE                                                           0.032
ES                                                           0.032
FI                                                           0.032
FR                                                           0.032
GR                                                           0.032
HR                                                           0.032
HU                                                           0.032
IE                                                           0.032
IT                                                           0.032
LT                                                           0.032
LU                                                           0.032
LV                                                           0.032
MT                                                           0.032
NL                                                           0.032
NO                                                           0.032
PO                                                           0.032
PT                                                           0.032
RO                                                           0.032
SE                                                           0.032
SI                                                           0.032
SK                                                           0.032
UK                                                           0.032
/;                                                                
                                                                  
