* Fuel potentials specified at geographical level.                                                                                                                          
* The fuel potential is specified as an upper limit on the countries'installed                                                                                              
* generation capacity relative to the individual fuel type.                                                                                                                 
* For now no limitations on fuel potential                                                                                                                                  
                                                                                                                                                                            
* Note: The value 0 or white space implies no restriction. The value 'eps' implies zero MW.                                                                                 
                                                                                                                                                                            
TABLE FKPOT(CCCRRRAAA,FFF)       'Fuel potential restriction by geography (MW)'                                                                                             
                                                                                            NUCLEAR LIGNITE ORIMULSION SHALE PEAT WATER STRAW WOOD WOODWASTE WIND SUN       
AUSTRIA                                                                                     0       0       0          0     0    0     0     0    0         0    0         
BELGIUM                                                                                     0       0       0          0     0    0     0     0    0         0    0         
BULGARIA                                                                                    0       0       0          0     0    0     0     0    0         0    0         
CROATIA                                                                                     0       0       0          0     0    0     0     0    0         0    0         
CYPRUS                                                                                      0       0       0          0     0    0     0     0    0         0    0         
CZECHIA                                                                                     0       0       0          0     0    0     0     0    0         0    0         
DENMARK                                                                                     0       0       0          0     0    0     0     0    0         0    0         
ESTONIA                                                                                     0       0       0          0     0    0     0     0    0         0    0         
FINLAND                                                                                     0       0       0          0     0    0     0     0    0         0    0         
FRANCE                                                                                      0       0       0          0     0    0     0     0    0         0    0         
GERMANY                                                                                     0       0       0          0     0    0     0     0    0         0    0         
GREECE                                                                                      0       0       0          0     0    0     0     0    0         0    0         
HUNGARY                                                                                     0       0       0          0     0    0     0     0    0         0    0         
IRELAND                                                                                     0       0       0          0     0    0     0     0    0         0    0         
ITALY                                                                                       0       0       0          0     0    0     0     0    0         0    0         
LATVIA                                                                                      0       0       0          0     0    0     0     0    0         0    0         
LITHUANIA                                                                                   0       0       0          0     0    0     0     0    0         0    0         
LUXEMBOURG                                                                                  0       0       0          0     0    0     0     0    0         0    0         
MALTA                                                                                       0       0       0          0     0    0     0     0    0         0    0         
NETHERLANDS                                                                                 0       0       0          0     0    0     0     0    0         0    0         
NORWAY                                                                                      0       0       0          0     0    0     0     0    0         0    0         
POLAND                                                                                      0       0       0          0     0    0     0     0    0         0    0         
PORTUGAL                                                                                    0       0       0          0     0    0     0     0    0         0    0         
ROMANIA                                                                                     0       0       0          0     0    0     0     0    0         0    0         
SLOVAKIA                                                                                    0       0       0          0     0    0     0     0    0         0    0         
SLOVENIA                                                                                    0       0       0          0     0    0     0     0    0         0    0         
SPAIN                                                                                       0       0       0          0     0    0     0     0    0         0    0         
SWEDEN                                                                                      0       0       0          0     0    0     0     0    0         0    0         
SWITZERLAND                                                                                 0       0       0          0     0    0     0     0    0         0    0         
UNITED_KINGDOM                                                                              0       0       0          0     0    0     0     0    0         0    0         
;                                                                                                                                                                           
