TABLE GEQF(YYY,CCCRRRAAA,FFF)  'Required fuel use (GJ) per year'                                                       
*                                                                NATGAS MUNIWASTE     STRAW       WOOD        WOODWASTE
*2016.DK2                                                               14930786                                       
;                                                                                                                      
