TABLE GMAXFS(YYY,CCCRRRAAA,FFF,SSS) 'Maximum fuel use (GJ) per year and season'                                    
*                                                                                              AT.MUNIWASTE.S01    
*2016                                                                                                              
*2017                                                                                                              
;                                                                                                                  
GMAXFS(YYY,CCCRRRAAA,FFF,SSS)$GMAXFS(YYY,CCCRRRAAA,FFF,'S01')=GMAXFS(YYY,CCCRRRAAA,FFF,'S01');                     
