TABLE GMAXF(YYY,CCCRRRAAA,FFF)  'Maximum fuel use (GJ) per year'                                               
*                                                                STRAW    WOOD      WOODWASTE BIOGAS   OTHERGAS
*2016.DENMARK                                                    92884745 211677970 5588136   39799851         
;                                                                                                              
*GMAXF(YYY,CCCRRRAAA,FFF)=GMAXF('2016',CCCRRRAAA,FFF);                                                         
