SET S(SSS)  'Seasons in the simulation'                                                        
/                                                                                              
*S29                                                                                           
*S09,S23,S32,S51                                                                               
S01*S52                                                                                        
/;                                                                                             
