                                                              
PARAMETER SOLEFLH(AAA)  'Full load hours for solar power'     
/                                                             
AT_A                                                      995 
BE_A                                                      806 
BE_Offshore                                               1   
BG_A                                                      800 
CH_A                                                      800 
CY_A                                                      800 
CY_Offshore                                               800 
CZ_A                                                      800 
DE_A                                                      922 
DE_Offshore                                               1   
DK_A                                                      822 
DK_Offshore                                               1   
EE_A                                                      800 
EE_Offshore                                               800 
ES_A                                                      800 
ES_Offshore                                               800 
FI_A                                                      800 
FI_Offshore                                               800 
FR_A                                                      1210
FR_Offshore                                               1   
GR_A                                                      800 
GR_Offshore                                               800 
HR_A                                                      800 
HR_Offshore                                               800 
HU_A                                                      800 
IE_A                                                      800 
IE_Offshore                                               800 
IT_A                                                      800 
IT_Offshore                                               800 
LT_A                                                      800 
LT_Offshore                                               800 
LU_A                                                      800 
LV_A                                                      800 
LV_Offshore                                               800 
MT_A                                                      800 
MT_Offshore                                               800 
NL_A                                                      850 
NL_Offshore                                               1   
NO_A                                                      800 
NO_Offshore                                               800 
PO_A                                                      800 
PO_Offshore                                               800 
PT_A                                                      800 
PT_Offshore                                               800 
RO_A                                                      800 
SE_A                                                      800 
SE_Offshore                                               800 
SI_A                                                      800 
SK_A                                                      800 
UK_A                                                      800 
UK_Offshore                                               800 
/;                                                            
*SOLEFLH(AAA)$(SOLEFLH(AAA) EQ 0) = SOLEFLH('AT_A') ;         
