PARAMETER      TAX_KN(YYY,AAA,G) 'Tax (neg. subsidy) for investment in electricity generation (mEUR90/MW)'  
/                                                                                                           
                                                                                                            
/;                                                                                                          
                                                                                                            
