TABLE TECHGROUPKPOT(CCCRRRAAA,TECH_GROUP)       'Technology group capacity restriction by geography (MW)'                                                               
                                                                                                          SOLARPV WINDTURBINE_ONSHORE WINDTURBINE_OFFSHORE              
AUSTRIA                                                                                                   0       0                   0                                 
BELGIUM                                                                                                   0       0                   0                                 
BULGARIA                                                                                                  0       0                   0                                 
CROATIA                                                                                                   0       0                   0                                 
CYPRUS                                                                                                    0       0                   0                                 
CZECHIA                                                                                                   0       0                   0                                 
DENMARK                                                                                                   0       0                   0                                 
ESTONIA                                                                                                   0       0                   0                                 
FINLAND                                                                                                   0       0                   0                                 
FRANCE                                                                                                    0       0                   0                                 
GERMANY                                                                                                   0       0                   0                                 
GREECE                                                                                                    0       0                   0                                 
HUNGARY                                                                                                   0       0                   0                                 
IRELAND                                                                                                   0       0                   0                                 
ITALY                                                                                                     0       0                   0                                 
LATVIA                                                                                                    0       0                   0                                 
LITHUANIA                                                                                                 0       0                   0                                 
LUXEMBOURG                                                                                                0       0                   0                                 
MALTA                                                                                                     0       0                   0                                 
NETHERLANDS                                                                                               0       0                   0                                 
NORWAY                                                                                                    0       0                   0                                 
POLAND                                                                                                    0       0                   0                                 
PORTUGAL                                                                                                  0       0                   0                                 
ROMANIA                                                                                                   0       0                   0                                 
SLOVAKIA                                                                                                  0       0                   0                                 
SLOVENIA                                                                                                  0       0                   0                                 
SPAIN                                                                                                     0       0                   0                                 
SWEDEN                                                                                                    0       0                   0                                 
SWITZERLAND                                                                                               0       0                   0                                 
UNITED_KINGDOM                                                                                            0       0                   0                                 
;                                                                                                                                                                       
