PARAMETER XMAXINV(IRRRE,IRRRI)   'Max investment in transmission capacity between two regions for each simulated year(each 5th year)'                           
/                                                                                                                                                               
$ontext                                                                                                                                                         
AT                                                                                                                                      .    CZ   1000          
AT                                                                                                                                      .    CH   1700          
AT                                                                                                                                      .    HU   1200          
AT                                                                                                                                      .    IT   1605          
AT                                                                                                                                      .    SI   2200          
AT                                                                                                                                      .    DE   7500          
CZ                                                                                                                                      .    AT   1200          
CH                                                                                                                                      .    AT   1700          
HU                                                                                                                                      .    AT   800           
IT                                                                                                                                      .    AT   1335          
SI                                                                                                                                      .    AT   2200          
DE                                                                                                                                      .    AT   7500          
CH                                                                                                                                      .    DE   4100          
DE                                                                                                                                      .    CH   6500          
CH                                                                                                                                      .    FR   5200          
FR                                                                                                                                      .    CH   3800          
CH                                                                                                                                      .    IT   3700          
IT                                                                                                                                      .    CH   6000          
CZ                                                                                                                                      .    DE   2000          
DE                                                                                                                                      .    CZ   2600          
CZ                                                                                                                                      .    PL   800           
PL                                                                                                                                      .    CZ   600           
CZ                                                                                                                                      .    SK   1100          
SK                                                                                                                                      .    CZ   2100          
DE                                                                                                                                      .    FR   5800          
FR                                                                                                                                      .    DE   5800          
DE                                                                                                                                      .    PL   3500          
PL                                                                                                                                      .    DE   3000          
FR                                                                                                                                      .    IT   4350          
IT                                                                                                                                      .    FR   2160          
HU                                                                                                                                      .    SI   1200          
SI                                                                                                                                      .    HU   1200          
HU                                                                                                                                      .    SK   2000          
SK                                                                                                                                      .    HU   2000          
PL                                                                                                                                      .    SK   990           
SK                                                                                                                                      .    PL   990           
ES                                                                                                                                      .    PT   1000          
PT                                                                                                                                      .    ES   1000          
ES                                                                                                                                      .    FR   1000          
FR                                                                                                                                      .    ES   1000          
$offtext                                                                                                                                                        
/;                                                                                                                                                              
                                                                                                                                                                
